# Generated by Django 5.1 on 2024-08-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_file',
        ),
    ]
