# Generated by Django 5.1 on 2024-08-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_file_remove_book_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sample_pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/sample_pdfs/'),
        ),
    ]
