# Generated by Django 5.1 on 2024-08-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_sample_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sample_pdf',
        ),
    ]
