# Generated by Django 5.1 on 2024-08-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
    ]
